server:
  port: 1110

spring:
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Liquibase gère le schéma
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    parameters:
      database.name: ${database.name}

  
database:
  host: 10.0.0.137
  port: 5432
  name: postgres_data_source
  username: postgres_data_source
  password: postgres_data_source