databaseChangeLog:
  - changeSet:
      id: 12
      author: jihed.chaabane
      changes:
        - insert:
            tableName: liquibase_oauth2_registered_client
            columns:
              - column:
                  name: id
                  valueComputed: gen_random_uuid()
              - column:
                  name: client_id
                  value: gr-oauth2-swagger-ms1
              - column:
                  name: client_secret
                  value: $2a$10$Im.5um3ZMJiCEts6vPtxAOA2XlSOfikHjtXEBN55wp6q.dUD9enkC
              - column:
                  name: scopes
                  value: read,write
              - column:
                  name: client_name
                  value: gr-oauth2-swagger-ms1--name
              - column:
                  name: authorization_grant_types
                  value: client_credentials
              - column:
                  name: client_authentication_methods
                  value: client_secret_basic
              - column:
                  name: client_id_issued_at
                  valueComputed: CURRENT_TIMESTAMP
              - column:
                  name: client_settings
                  value: '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":false}'
              - column:
                  name: token_settings
                  value: '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.id-token-signature-algorithm":"RS256","settings.token.access-token-time-to-live":["java.time.Duration",1800.000000000],"settings.token.access-token-format":"self-contained","settings.token.refresh-token-time-to-live":["java.time.Duration",3600.000000000]}'
        - insert:
            tableName: liquibase_oauth2_registered_client
            columns:
              - column:
                  name: id
                  valueComputed: gen_random_uuid()
              - column:
                  name: client_id
                  value: gr-oauth2-swagger-ms2
              - column:
                  name: client_secret
                  value: $2a$10$aWLny8W3WhUe6dUnVthhSeyCbvAE952WeNzM58BGaqKHIYlgMKaXS
              - column:
                  name: scopes
                  value: update,remove
              - column:
                  name: client_name
                  value: gr-oauth2-swagger-ms2--name
              - column:
                  name: authorization_grant_types
                  value: client_credentials
              - column:
                  name: client_authentication_methods
                  value: client_secret_basic
              - column:
                  name: client_id_issued_at
                  valueComputed: CURRENT_TIMESTAMP
              - column:
                  name: client_settings
                  value: '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":false}'
              - column:
                  name: token_settings
                  value: '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.id-token-signature-algorithm":"RS256","settings.token.access-token-time-to-live":["java.time.Duration",1800.000000000],"settings.token.access-token-format":"self-contained","settings.token.refresh-token-time-to-live":["java.time.Duration",3600.000000000]}'